[workspace]
members = [
	"rustris",
	"paint",
	"compute",
	"dyn_link_test",
]

[profile.dev]
codegen-units = 32
incremental = true
overflow-checks = true
debug-assertions = true
lto = false
debug = true
opt-level = 0
panic = "abort"
#linker-flavor = "ld64.lld"